CREATE TABLE "baits" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "baits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"icon_url" text NOT NULL,
	"description" text NOT NULL,
	"fish_type" text,
	"bonuses" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "baits_slug_unique" UNIQUE("slug"),
	CONSTRAINT "baits_name_unique" UNIQUE("name")
);
--> statement-breakpoint
-- Generated by scripts/import-baits.py. Preserves bait IDs.
INSERT INTO baits (slug, name, description, icon_url, fish_type, bonuses) VALUES
('shrimp-bait', 'Shrimp Bait', 'Shrimp and fish-based bait loved by big fish. Fish that consume this type of bait grow quickly.', '/baits/shrimp-bait.png', NULL, '[{"name": "Mastery", "percent": 25}]'::jsonb),
('lucky-star', 'Lucky Star', 'According to legend, this material comes from the sky, filled with unknown and mysterious properties, seemingly related to certain mysterious items.', '/baits/lucky-star.png', NULL, '[{"name": "Scavenge", "percent": 10}, {"name": "Mastery", "percent": 10}]'::jsonb),
('mealworm', 'Mealworm', 'A type of bait loved by small fish. Fish that consume this type of bait grow quickly.', '/baits/mealworm.png', 'Small', '[{"name": "Small Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('pupa-bait', 'Pupa Bait', 'A type of bait loved by medium fish. Fish that consume this type of bait grow quickly.', '/baits/pupa-bait.png', 'Medium', '[{"name": "Medium Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('mudskipper', 'Mudskipper', 'A type of bait loved by large fish. Fish that consume this type of bait grow quickly.', '/baits/mudskipper.png', 'Large', '[{"name": "Large Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('seaweed-bait', 'Seaweed Bait', 'A type of bait loved by underwater creatures. Creatures that consume this type of bait grow quickly.', '/baits/seaweed-bait.png', 'Aquatic', '[{"name": "Biologist", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('earthworm', 'Earthworm', 'A type of bait loved by small fish', '/baits/earthworm.png', 'Small', '[{"name": "Small Fish Hunter", "percent": 30}]'::jsonb),
('beetle-bait', 'Beetle Bait', 'A type of bait loved by medium fish', '/baits/beetle-bait.png', 'Medium', '[{"name": "Medium Fish Hunter", "percent": 30}]'::jsonb),
('locust-bait', 'Locust Bait', 'A type of bait loved by large fish', '/baits/locust-bait.png', 'Large', '[{"name": "Large Fish Hunter", "percent": 30}]'::jsonb),
('mayfly', 'Mayfly Bait', 'A type of bait loved by underwater creatures', '/baits/mayfly.png', 'Aquatic', '[{"name": "Biologist", "percent": 30}]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, icon_url = EXCLUDED.icon_url, fish_type = EXCLUDED.fish_type, bonuses = EXCLUDED.bonuses;
--> statement-breakpoint
UPDATE fishes SET bait = 'Mayfly Bait' WHERE bait = 'Mayfly';
--> statement-breakpoint
ALTER TABLE "fishes" ADD CONSTRAINT "fishes_bait_baits_name_fk" FOREIGN KEY ("bait") REFERENCES "public"."baits"("name") ON DELETE set null ON UPDATE cascade;
--> statement-breakpoint
ALTER TABLE "baits" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "lineup_app_all" ON "baits" FOR ALL TO "lineup_app" USING (true) WITH CHECK (true);
--> statement-breakpoint
GRANT ALL ON TABLE "baits" TO "lineup_app";
--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE "baits_id_seq" TO "lineup_app";
