#!/usr/bin/env python3
"""Import the owner's fish area sheets, excluding fishing collectibles.

Writes src/data/fishes.ts and scripts/upsert-fishes.sql. The upsert preserves
existing fish IDs and lineup selections. Icon sources and screenshot-corrected
names are recorded in gameplay/fishes/icons.json.
Names and stat wording are preserved, with surrounding whitespace removed.
"""

import csv
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
AREAS = (
    "Gold Coast", "Moonlight Canyon", "Snowy Mountain", "Desert Beach",
    "Frost Land", "Jungle Lakes", "Idyllic Paradise",
)
HEADERS = ["Fish Name", "Type", "Collection", "Stat 1", "Stat 2", "Stat 3", "Bait"]
FISH_TYPES = {"Small", "Medium", "Large", "Aquatic"}
BASE_STATS = {"ATK", "HP", "DEF"} | {
    f"{role} {stat}" for role in ("Warrior", "Marksman", "Mage", "Support")
    for stat in ("ATK", "HP")
}


def add_details(fishes: list[dict], directory: Path) -> list[dict]:
    from PIL import Image

    icons = json.loads((directory / "icons.json").read_text())
    baits = {row["slug"]: row["name"] for row in json.loads((directory / "baits.json").read_text())}
    if set(icons) != {fish["slug"] for fish in fishes}:
        raise ValueError("Icon manifest must cover exactly the fish catalog")
    for fish in fishes:
        if fish["bait"]:
            slug = re.sub(r"[^a-z0-9]+", "-", fish["bait"].lower()).strip("-")
            if slug not in baits:
                raise ValueError(f"Unknown bait for {fish['slug']}: {fish['bait']}")
            fish["bait"] = baits[slug]
        icon = icons[fish["slug"]]
        source = directory / icon["source"]
        if source.parent != directory or not icon["name"].strip():
            raise ValueError(f"Invalid icon source or name: {fish['slug']}")
        with Image.open(source) as image:
            if image.size != (604, 444):
                raise ValueError(f"Unexpected screenshot dimensions: {source}")
        fish.update(
            name=icon["name"],
            iconUrl=f"/fishes/{fish['slug']}.png",
            baseStats=[stat for stat in fish["stats"] if stat in BASE_STATS],
            specialStats=[stat for stat in fish["stats"] if stat not in BASE_STATS],
        )
    return fishes


def write_icons(fishes: list[dict], directory: Path, output: Path):
    from PIL import Image

    icons = json.loads((directory / "icons.json").read_text())
    output.mkdir(parents=True, exist_ok=True)
    for fish in fishes:
        with Image.open(directory / icons[fish["slug"]]["source"]) as image:
            # The complete circular icon panel, excluding the title and record.
            image.crop((35, 87, 165, 217)).save(output / f"{fish['slug']}.png")


def read_fishes(directory: Path) -> list[dict]:
    fishes = []
    slugs = set()
    for area in AREAS:
        path = directory / f"Fish Guide - {area}.csv"
        with path.open(encoding="utf-8-sig", newline="") as source:
            reader = csv.DictReader(source)
            if reader.fieldnames != HEADERS:
                raise ValueError(f"{path.name}: expected fish sheet columns")
            count = 0
            for row in reader:
                if None in row or any(value is None for value in row.values()):
                    raise ValueError(f"{path.name}:{reader.line_num}: malformed row")
                row = {key: value.strip() for key, value in row.items()}
                if not any(row.values()):
                    continue
                name = row["Fish Name"]
                slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
                if not slug or slug in slugs:
                    raise ValueError(f"{path.name}:{reader.line_num}: empty or duplicate fish: {name}")
                if row["Type"] not in FISH_TYPES or not row["Collection"]:
                    raise ValueError(f"{path.name}:{reader.line_num}: missing collection or invalid type")
                slugs.add(slug)
                fishes.append({
                    "slug": slug,
                    "name": name,
                    "area": area,
                    "fishType": row["Type"],
                    "collection": row["Collection"],
                    "stats": [row[f"Stat {i}"] for i in (1, 2, 3)
                              if row[f"Stat {i}"] not in ("", "-")],
                    "bait": row["Bait"] if row["Bait"] not in ("", "-") else None,
                })
                count += 1
            if not count:
                raise ValueError(f"{path.name}: no fishes found")
    return fishes


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main():
    directory = ROOT / "gameplay/fishes"
    fishes = add_details(read_fishes(directory), directory)
    write_icons(fishes, directory, ROOT / "public/fishes")
    seed = '''/** Generated by scripts/import-fishes.py from the owner's sheets and screenshots. */
export type FishSeed = {
  slug: string;
  name: string;
  area: string;
  fishType: string;
  collection: string;
  stats: string[];
  bait: string | null;
  iconUrl: string;
  baseStats: string[];
  specialStats: string[];
};

export const fishSeeds: FishSeed[] = [
'''
    for fish in fishes:
        seed += "  {\n"
        for key, value in fish.items():
            seed += f"    {key}: {json.dumps(value, ensure_ascii=False)},\n"
        seed += "  },\n"
    seed += "];\n"
    (ROOT / "src/data/fishes.ts").write_text(seed)

    values = []
    for fish in fishes:
        columns = [sql_string(fish[key]) for key in
                   ("slug", "name", "area", "fishType", "collection")]
        columns.append("ARRAY[" + ", ".join(map(sql_string, fish["stats"])) + "]::text[]")
        columns.append(sql_string(fish["bait"]) if fish["bait"] else "NULL")
        columns.append(sql_string(fish["iconUrl"]))
        for key in ("baseStats", "specialStats"):
            columns.append("ARRAY[" + ", ".join(map(sql_string, fish[key])) + "]::text[]")
        values.append("(" + ", ".join(columns) + ")")
    sql = "-- Generated by scripts/import-fishes.py. Preserves IDs and lineup links.\n"
    sql += "INSERT INTO fishes (slug, name, area, fish_type, collection, stats, bait, icon_url, base_stats, special_stats) VALUES\n"
    sql += ",\n".join(values)
    sql += "\nON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, area = EXCLUDED.area,"
    sql += " fish_type = EXCLUDED.fish_type, collection = EXCLUDED.collection,"
    sql += " stats = EXCLUDED.stats, bait = EXCLUDED.bait, icon_url = EXCLUDED.icon_url,"
    sql += " base_stats = EXCLUDED.base_stats, special_stats = EXCLUDED.special_stats;\n"
    (ROOT / "scripts/upsert-fishes.sql").write_text(sql)
    print(f"Imported {len(fishes)} fishes from {len(AREAS)} area sheets.")


if __name__ == "__main__":
    main()
