#!/usr/bin/env python3
"""Import the owner's fish area sheets, excluding fishing collectibles.

Writes src/data/fishes.ts and scripts/upsert-fishes.sql. The upsert preserves
existing fish IDs and lineup selections; it does not replace recorded icons.
Names and stat wording are preserved, with surrounding whitespace removed.
"""

import csv
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
AREAS = (
    "Gold Coast", "Moonlight Canyon", "Snowy Mountain", "Desert Beach",
    "Frost Land", "Jungle Lakes", "Idyllic Paradise",
)
HEADERS = ["Fish Name", "Type", "Collection", "Stat 1", "Stat 2", "Stat 3", "Bait"]
FISH_TYPES = {"Small", "Medium", "Large", "Aquatic"}


def read_fishes(directory: Path) -> list[dict]:
    fishes = []
    slugs = set()
    for area in AREAS:
        path = directory / f"Fish Guide - {area}.csv"
        with path.open(encoding="utf-8-sig", newline="") as source:
            reader = csv.DictReader(source)
            if reader.fieldnames != HEADERS:
                raise ValueError(f"{path.name}: expected fish sheet columns")
            count = 0
            for row in reader:
                if None in row or any(value is None for value in row.values()):
                    raise ValueError(f"{path.name}:{reader.line_num}: malformed row")
                row = {key: value.strip() for key, value in row.items()}
                if not any(row.values()):
                    continue
                name = row["Fish Name"]
                slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
                if not slug or slug in slugs:
                    raise ValueError(f"{path.name}:{reader.line_num}: empty or duplicate fish: {name}")
                if row["Type"] not in FISH_TYPES or not row["Collection"]:
                    raise ValueError(f"{path.name}:{reader.line_num}: missing collection or invalid type")
                slugs.add(slug)
                fishes.append({
                    "slug": slug,
                    "name": name,
                    "area": area,
                    "fishType": row["Type"],
                    "collection": row["Collection"],
                    "stats": [row[f"Stat {i}"] for i in (1, 2, 3)
                              if row[f"Stat {i}"] not in ("", "-")],
                    "bait": row["Bait"] if row["Bait"] not in ("", "-") else None,
                })
                count += 1
            if not count:
                raise ValueError(f"{path.name}: no fishes found")
    return fishes


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main():
    fishes = read_fishes(ROOT / "gameplay/fishes")
    seed = '''/** Generated by scripts/import-fishes.py from the owner's area sheets. */
export type FishSeed = {
  slug: string;
  name: string;
  area: string;
  fishType: string;
  collection: string;
  stats: string[];
  bait: string | null;
};

export const fishSeeds: FishSeed[] = [
'''
    for fish in fishes:
        seed += "  {\n"
        for key, value in fish.items():
            seed += f"    {key}: {json.dumps(value, ensure_ascii=False)},\n"
        seed += "  },\n"
    seed += "];\n"
    (ROOT / "src/data/fishes.ts").write_text(seed)

    values = []
    for fish in fishes:
        columns = [sql_string(fish[key]) for key in
                   ("slug", "name", "area", "fishType", "collection")]
        columns.append("ARRAY[" + ", ".join(map(sql_string, fish["stats"])) + "]::text[]")
        columns.append(sql_string(fish["bait"]) if fish["bait"] else "NULL")
        values.append("(" + ", ".join(columns) + ")")
    sql = "-- Generated by scripts/import-fishes.py. Preserves IDs, lineup links, and icons.\n"
    sql += "INSERT INTO fishes (slug, name, area, fish_type, collection, stats, bait) VALUES\n"
    sql += ",\n".join(values)
    sql += "\nON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, area = EXCLUDED.area,"
    sql += " fish_type = EXCLUDED.fish_type, collection = EXCLUDED.collection,"
    sql += " stats = EXCLUDED.stats, bait = EXCLUDED.bait;\n"
    (ROOT / "scripts/upsert-fishes.sql").write_text(sql)
    print(f"Imported {len(fishes)} fishes from {len(AREAS)} area sheets.")


if __name__ == "__main__":
    main()
