#!/usr/bin/env python3
"""Generate bait seeds, SQL and icons from the reviewed owner screenshot manifest.

Recorded bonuses are the percentages shown in these screenshots, not inferred
maximums. The icon crop excludes the account's quantity badge and shop controls.
"""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def read_baits(directory):
    rows = json.loads((directory / "baits.json").read_text())
    if len({row["slug"] for row in rows}) != len(rows) or len({row["name"] for row in rows}) != len(rows):
        raise ValueError("Duplicate bait slug or name")
    for row in rows:
        if row["fishType"] not in (None, "Small", "Medium", "Large", "Aquatic"):
            raise ValueError(f"Invalid bait fish category: {row['slug']}")
        source = directory / row["source"]
        if source.parent != directory:
            raise ValueError("Invalid bait source")
        with Image.open(source) as image:
            if image.size != (604, 526):
                raise ValueError(f"Unexpected bait screenshot dimensions: {source}")
    return rows


def main():
    directory = ROOT / "gameplay/fishes"
    rows = read_baits(directory)
    output = ROOT / "public/baits"
    output.mkdir(parents=True, exist_ok=True)
    seeds = []
    for row in rows:
        with Image.open(directory / row["source"]) as image:
            # Entire bait art, above the quantity badge at y=140.
            image.crop((62, 67, 140, 139)).save(output / f"{row['slug']}.png")
        seeds.append({key: value for key, value in row.items() if key != "source"} | {
            "iconUrl": f"/baits/{row['slug']}.png",
        })
    seed = '''/** Generated by scripts/import-baits.py from the owner's screenshots. */
export type BaitSeed = {
  slug: string;
  name: string;
  description: string;
  fishType: string | null;
  bonuses: { name: string; percent: number }[];
  iconUrl: string;
};

export const baitSeeds: BaitSeed[] = ''' + json.dumps(seeds, ensure_ascii=False, indent=2) + ";\n"
    (ROOT / "src/data/baits.ts").write_text(seed)
    values = []
    for bait in seeds:
        columns = [sql_string(bait[key]) for key in ("slug", "name", "description", "iconUrl")]
        columns += [sql_string(bait["fishType"]) if bait["fishType"] else "NULL",
                    sql_string(json.dumps(bait["bonuses"])) + "::jsonb"]
        values.append("(" + ", ".join(columns) + ")")
    sql = "-- Generated by scripts/import-baits.py. Preserves bait IDs.\n"
    sql += "INSERT INTO baits (slug, name, description, icon_url, fish_type, bonuses) VALUES\n"
    sql += ",\n".join(values)
    sql += "\nON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,"
    sql += " icon_url = EXCLUDED.icon_url, fish_type = EXCLUDED.fish_type, bonuses = EXCLUDED.bonuses;\n"
    (ROOT / "scripts/upsert-baits.sql").write_text(sql)
    print(f"Imported {len(seeds)} baits.")


if __name__ == "__main__":
    main()
