#!/usr/bin/env python3
"""Extract the owner's eight relic icon tiles and generate their name catalog.

Run: python3 scripts/slice-relics.py (requires Pillow).
The supplied gameplay/relics/image.png contains clean icon tiles. Names are
verified against the corresponding Relic Archive popups; omit their +15 suffix.
The source coordinates below preserve each complete tile at native resolution.
"""

import json
from pathlib import Path
import re

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "gameplay/relics"
OUTPUT = ROOT / "public/relics"

# Name, popup timestamp on 2026-09-13, icon tile bounds in image.png.
CATALOG = [
    ("Night Twinblades", "12.57.40", (9, 9, 110, 110)),
    ("Charge Shield", "12.57.44", (125, 9, 226, 110)),
    ("Spiked Armor", "12.57.47", (241, 9, 342, 110)),
    ("Soulcalm Gem", "12.57.49", (357, 9, 458, 110)),
    ("Boots of Haste", "12.58.06", (473, 9, 574, 110)),
    ("Silverblade", "12.58.09", (9, 118, 110, 219)),
    ("Pendant of Purity", "12.58.12", (125, 118, 226, 219)),
    ("Arcane Cloak", "12.58.16", (241, 118, 342, 219)),
]


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def main():
    with Image.open(SOURCE / "image.png") as sheet:
        if sheet.size != (590, 232):
            raise ValueError("Relic icon sheet dimensions changed; recheck tile bounds")
        for _, time, bounds in CATALOG:
            popup = SOURCE / f"Screenshot 2026-09-13 at {time}\u202fPM.png"
            if not popup.is_file():
                raise FileNotFoundError(popup)
            if not (0 <= bounds[0] < bounds[2] <= sheet.width and 0 <= bounds[1] < bounds[3] <= sheet.height):
                raise ValueError(f"Invalid relic tile bounds: {bounds}")

        OUTPUT.mkdir(parents=True, exist_ok=True)
        rows = []
        for name, _, bounds in CATALOG:
            slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
            sheet.crop(bounds).save(OUTPUT / f"{slug}.png", optimize=True)
            rows.append({"slug": slug, "name": name, "iconUrl": f"/relics/{slug}.png"})

    (ROOT / "src/data/relics.ts").write_text(
        "/** Names and icons from gameplay/relics; generated by scripts/slice-relics.py. */\n"
        "export type RelicSeed = { slug: string; name: string; iconUrl: string };\n\n"
        "export const relicSeeds: RelicSeed[] = " + json.dumps(rows, indent=2) + ";\n",
        encoding="utf-8",
    )
    values = ",\n".join(
        "(" + ", ".join(sql_string(row[key]) for key in ("slug", "name", "iconUrl")) + ")"
        for row in rows
    )
    (ROOT / "scripts/upsert-relics.sql").write_text(
        "-- Generated by scripts/slice-relics.py; preserves IDs on repeated imports.\n"
        "INSERT INTO relics (slug, name, icon_url) VALUES\n" + values + "\n"
        "ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, icon_url = EXCLUDED.icon_url;\n",
        encoding="utf-8",
    )
    print(f"Extracted {len(rows)} relic icons and generated the TypeScript and SQL catalogs.")


if __name__ == "__main__":
    main()
