-- Generated by scripts/slice-relics.py; preserves IDs on repeated imports.
INSERT INTO relics (slug, name, icon_url) VALUES
('night-twinblades', 'Night Twinblades', '/relics/night-twinblades.png'),
('charge-shield', 'Charge Shield', '/relics/charge-shield.png'),
('spiked-armor', 'Spiked Armor', '/relics/spiked-armor.png'),
('soulcalm-gem', 'Soulcalm Gem', '/relics/soulcalm-gem.png'),
('boots-of-haste', 'Boots of Haste', '/relics/boots-of-haste.png'),
('silverblade', 'Silverblade', '/relics/silverblade.png'),
('pendant-of-purity', 'Pendant of Purity', '/relics/pendant-of-purity.png'),
('arcane-cloak', 'Arcane Cloak', '/relics/arcane-cloak.png')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, icon_url = EXCLUDED.icon_url;
