-- Generated by scripts/import-baits.py. Preserves bait IDs.
INSERT INTO baits (slug, name, description, icon_url, fish_type, bonuses) VALUES
('shrimp-bait', 'Shrimp Bait', 'Shrimp and fish-based bait loved by big fish. Fish that consume this type of bait grow quickly.', '/baits/shrimp-bait.png', NULL, '[{"name": "Mastery", "percent": 25}]'::jsonb),
('lucky-star', 'Lucky Star', 'According to legend, this material comes from the sky, filled with unknown and mysterious properties, seemingly related to certain mysterious items.', '/baits/lucky-star.png', NULL, '[{"name": "Scavenge", "percent": 10}, {"name": "Mastery", "percent": 10}]'::jsonb),
('mealworm', 'Mealworm', 'A type of bait loved by small fish. Fish that consume this type of bait grow quickly.', '/baits/mealworm.png', 'Small', '[{"name": "Small Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('pupa-bait', 'Pupa Bait', 'A type of bait loved by medium fish. Fish that consume this type of bait grow quickly.', '/baits/pupa-bait.png', 'Medium', '[{"name": "Medium Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('mudskipper', 'Mudskipper', 'A type of bait loved by large fish. Fish that consume this type of bait grow quickly.', '/baits/mudskipper.png', 'Large', '[{"name": "Large Fish Hunter", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('seaweed-bait', 'Seaweed Bait', 'A type of bait loved by underwater creatures. Creatures that consume this type of bait grow quickly.', '/baits/seaweed-bait.png', 'Aquatic', '[{"name": "Biologist", "percent": 35}, {"name": "Mastery", "percent": 10}]'::jsonb),
('earthworm', 'Earthworm', 'A type of bait loved by small fish', '/baits/earthworm.png', 'Small', '[{"name": "Small Fish Hunter", "percent": 30}]'::jsonb),
('beetle-bait', 'Beetle Bait', 'A type of bait loved by medium fish', '/baits/beetle-bait.png', 'Medium', '[{"name": "Medium Fish Hunter", "percent": 30}]'::jsonb),
('locust-bait', 'Locust Bait', 'A type of bait loved by large fish', '/baits/locust-bait.png', 'Large', '[{"name": "Large Fish Hunter", "percent": 30}]'::jsonb),
('mayfly', 'Mayfly Bait', 'A type of bait loved by underwater creatures', '/baits/mayfly.png', 'Aquatic', '[{"name": "Biologist", "percent": 30}]'::jsonb)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, icon_url = EXCLUDED.icon_url, fish_type = EXCLUDED.fish_type, bonuses = EXCLUDED.bonuses;
