-- Generated by scripts/slice-pets.py. Run against Supabase to sync pet names and icons.
INSERT INTO pets (slug, name, icon_url) VALUES
('mystic-witch', 'Mystic Witch', '/pets/mystic-witch.png'),
('arcane-lady', 'Arcane Lady', '/pets/arcane-lady.png'),
('doom-fang', 'Doom Fang', '/pets/doom-fang.png'),
('emerald-lord', 'Emerald Lord', '/pets/emerald-lord.png'),
('scarlet-comet', 'Scarlet Comet', '/pets/scarlet-comet.png'),
('earth-tyrant', 'Earth Tyrant', '/pets/earth-tyrant.png'),
('zathum', 'Zathum', '/pets/zathum.png'),
('blaze-monkey', 'Blaze Monkey', '/pets/blaze-monkey.png'),
('mecha-beetle', 'Mecha Beetle', '/pets/mecha-beetle.png'),
('tinman-no-7', 'Tinman No.7', '/pets/tinman-no-7.png'),
('stellar-whale', 'Stellar Whale', '/pets/stellar-whale.png'),
('rockturtle', 'Rockturtle', '/pets/rockturtle.png'),
('magic-owl', 'Magic Owl', '/pets/magic-owl.png'),
('giant-crabs', 'Giant Crabs', '/pets/giant-crabs.png'),
('yoyo-fox', 'Yoyo Fox', '/pets/yoyo-fox.png'),
('sparky', 'Sparky', '/pets/sparky.png'),
('kindwing', 'Kindwing', '/pets/kindwing.png'),
('mini-shroom', 'Mini Shroom', '/pets/mini-shroom.png'),
('emberling', 'Emberling', '/pets/emberling.png'),
('pea-fish', 'Pea Fish', '/pets/pea-fish.png')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, icon_url = EXCLUDED.icon_url;
