/** Generated by scripts/import-baits.py from the owner's screenshots. */
export type BaitSeed = {
  slug: string;
  name: string;
  description: string;
  fishType: string | null;
  bonuses: { name: string; percent: number }[];
  iconUrl: string;
};

export const baitSeeds: BaitSeed[] = [
  {
    slug: "shrimp-bait",
    name: "Shrimp Bait",
    description:
      "Shrimp and fish-based bait loved by big fish. Fish that consume this type of bait grow quickly.",
    fishType: null,
    bonuses: [
      {
        name: "Mastery",
        percent: 25,
      },
    ],
    iconUrl: "/baits/shrimp-bait.png",
  },
  {
    slug: "lucky-star",
    name: "Lucky Star",
    description:
      "According to legend, this material comes from the sky, filled with unknown and mysterious properties, seemingly related to certain mysterious items.",
    fishType: null,
    bonuses: [
      {
        name: "Scavenge",
        percent: 10,
      },
      {
        name: "Mastery",
        percent: 10,
      },
    ],
    iconUrl: "/baits/lucky-star.png",
  },
  {
    slug: "mealworm",
    name: "Mealworm",
    description:
      "A type of bait loved by small fish. Fish that consume this type of bait grow quickly.",
    fishType: "Small",
    bonuses: [
      {
        name: "Small Fish Hunter",
        percent: 35,
      },
      {
        name: "Mastery",
        percent: 10,
      },
    ],
    iconUrl: "/baits/mealworm.png",
  },
  {
    slug: "pupa-bait",
    name: "Pupa Bait",
    description:
      "A type of bait loved by medium fish. Fish that consume this type of bait grow quickly.",
    fishType: "Medium",
    bonuses: [
      {
        name: "Medium Fish Hunter",
        percent: 35,
      },
      {
        name: "Mastery",
        percent: 10,
      },
    ],
    iconUrl: "/baits/pupa-bait.png",
  },
  {
    slug: "mudskipper",
    name: "Mudskipper",
    description:
      "A type of bait loved by large fish. Fish that consume this type of bait grow quickly.",
    fishType: "Large",
    bonuses: [
      {
        name: "Large Fish Hunter",
        percent: 35,
      },
      {
        name: "Mastery",
        percent: 10,
      },
    ],
    iconUrl: "/baits/mudskipper.png",
  },
  {
    slug: "seaweed-bait",
    name: "Seaweed Bait",
    description:
      "A type of bait loved by underwater creatures. Creatures that consume this type of bait grow quickly.",
    fishType: "Aquatic",
    bonuses: [
      {
        name: "Biologist",
        percent: 35,
      },
      {
        name: "Mastery",
        percent: 10,
      },
    ],
    iconUrl: "/baits/seaweed-bait.png",
  },
  {
    slug: "earthworm",
    name: "Earthworm",
    description: "A type of bait loved by small fish",
    fishType: "Small",
    bonuses: [
      {
        name: "Small Fish Hunter",
        percent: 30,
      },
    ],
    iconUrl: "/baits/earthworm.png",
  },
  {
    slug: "beetle-bait",
    name: "Beetle Bait",
    description: "A type of bait loved by medium fish",
    fishType: "Medium",
    bonuses: [
      {
        name: "Medium Fish Hunter",
        percent: 30,
      },
    ],
    iconUrl: "/baits/beetle-bait.png",
  },
  {
    slug: "locust-bait",
    name: "Locust Bait",
    description: "A type of bait loved by large fish",
    fishType: "Large",
    bonuses: [
      {
        name: "Large Fish Hunter",
        percent: 30,
      },
    ],
    iconUrl: "/baits/locust-bait.png",
  },
  {
    slug: "mayfly",
    name: "Mayfly Bait",
    description: "A type of bait loved by underwater creatures",
    fishType: "Aquatic",
    bonuses: [
      {
        name: "Biologist",
        percent: 30,
      },
    ],
    iconUrl: "/baits/mayfly.png",
  },
];
