/**
 * Divinity catalog read from the owner's in-game popups (gameplay/divinities).
 * Generated by scripts/slice-divinities.py — edit CATALOG there, not this file.
 */
export type DivinitySeed = {
  slug: string;
  name: string;
  kind: string;
  iconUrl: string;
};

export const divinitySeeds: DivinitySeed[] = [
  { slug: "atk", name: "ATK", kind: "ATK", iconUrl: "/divinities/atk.png" },
  {
    slug: "mage-atk",
    name: "Mage ATK",
    kind: "ATK",
    iconUrl: "/divinities/mage-atk.png",
  },
  {
    slug: "support-atk",
    name: "Support ATK",
    kind: "ATK",
    iconUrl: "/divinities/support-atk.png",
  },
  {
    slug: "warrior-atk",
    name: "Warrior ATK",
    kind: "ATK",
    iconUrl: "/divinities/warrior-atk.png",
  },
  { slug: "def", name: "DEF", kind: "DEF", iconUrl: "/divinities/def.png" },
  {
    slug: "marksman-def",
    name: "Marksman DEF",
    kind: "DEF",
    iconUrl: "/divinities/marksman-def.png",
  },
  { slug: "hp", name: "HP", kind: "HP", iconUrl: "/divinities/hp.png" },
  {
    slug: "dmg-increase",
    name: "DMG Increase",
    kind: "DMG Increase",
    iconUrl: "/divinities/dmg-increase.png",
  },
  {
    slug: "physical-dmg-boost",
    name: "Physical DMG Boost",
    kind: "DMG Increase",
    iconUrl: "/divinities/physical-dmg-boost.png",
  },
  {
    slug: "magic-dmg-boost",
    name: "Magic DMG Boost",
    kind: "DMG Increase",
    iconUrl: "/divinities/magic-dmg-boost.png",
  },
  {
    slug: "melee-dmg-boost",
    name: "Melee DMG Boost",
    kind: "DMG Increase",
    iconUrl: "/divinities/melee-dmg-boost.png",
  },
  {
    slug: "ranged-dmg-boost",
    name: "Ranged DMG Boost",
    kind: "DMG Increase",
    iconUrl: "/divinities/ranged-dmg-boost.png",
  },
  {
    slug: "dmg-reduction",
    name: "DMG Reduction",
    kind: "DMG Reduction",
    iconUrl: "/divinities/dmg-reduction.png",
  },
  {
    slug: "physical-res",
    name: "Physical RES",
    kind: "DMG Reduction",
    iconUrl: "/divinities/physical-res.png",
  },
  {
    slug: "magic-res",
    name: "Magic RES",
    kind: "DMG Reduction",
    iconUrl: "/divinities/magic-res.png",
  },
  {
    slug: "melee-dmg-reduction",
    name: "Melee DMG Reduction",
    kind: "DMG Reduction",
    iconUrl: "/divinities/melee-dmg-reduction.png",
  },
  {
    slug: "ranged-dmg-reduction",
    name: "Ranged DMG Reduction",
    kind: "DMG Reduction",
    iconUrl: "/divinities/ranged-dmg-reduction.png",
  },
  {
    slug: "crit-rate",
    name: "CRIT Rate",
    kind: "CRIT",
    iconUrl: "/divinities/crit-rate.png",
  },
  {
    slug: "crit-damage",
    name: "CRIT Damage",
    kind: "CRIT",
    iconUrl: "/divinities/crit-damage.png",
  },
  {
    slug: "anti-control-rate",
    name: "Anti-Control Rate",
    kind: "RES",
    iconUrl: "/divinities/anti-control-rate.png",
  },
  {
    slug: "control-res",
    name: "Control RES",
    kind: "RES",
    iconUrl: "/divinities/control-res.png",
  },
  {
    slug: "crit-dmg-reduction",
    name: "CRIT DMG Reduction",
    kind: "RES",
    iconUrl: "/divinities/crit-dmg-reduction.png",
  },
  {
    slug: "anti-crit-rate",
    name: "Anti-CRIT Rate",
    kind: "RES",
    iconUrl: "/divinities/anti-crit-rate.png",
  },
  {
    slug: "knockback-effect",
    name: "Knockback Effect",
    kind: "Knockback",
    iconUrl: "/divinities/knockback-effect.png",
  },
  {
    slug: "knockback-resist",
    name: "Knockback Resist",
    kind: "Knockback",
    iconUrl: "/divinities/knockback-resist.png",
  },
  {
    slug: "spd-reduction-res",
    name: "SPD Reduction RES",
    kind: "Knockback",
    iconUrl: "/divinities/spd-reduction-res.png",
  },
  {
    slug: "heavy-injury",
    name: "Heavy Injury",
    kind: "Healing",
    iconUrl: "/divinities/heavy-injury.png",
  },
  {
    slug: "healing-effect",
    name: "Healing Effect",
    kind: "Healing",
    iconUrl: "/divinities/healing-effect.png",
  },
  {
    slug: "receive-healing",
    name: "Receive Healing",
    kind: "Healing",
    iconUrl: "/divinities/receive-healing.png",
  },
  {
    slug: "atk-spd",
    name: "ATK SPD",
    kind: "SPD Boost",
    iconUrl: "/divinities/atk-spd.png",
  },
];
