/**
 * Pet names and icons from the owner's gameplay/pets screenshots.
 * Generated by scripts/slice-pets.py — edit CATALOG there.
 */
export type PetSeed = {
  slug: string;
  name: string;
  iconUrl: string;
};

export const petSeeds: PetSeed[] = [
  {
    slug: "mystic-witch",
    name: "Mystic Witch",
    iconUrl: "/pets/mystic-witch.png",
  },
  {
    slug: "arcane-lady",
    name: "Arcane Lady",
    iconUrl: "/pets/arcane-lady.png",
  },
  {
    slug: "doom-fang",
    name: "Doom Fang",
    iconUrl: "/pets/doom-fang.png",
  },
  {
    slug: "emerald-lord",
    name: "Emerald Lord",
    iconUrl: "/pets/emerald-lord.png",
  },
  {
    slug: "scarlet-comet",
    name: "Scarlet Comet",
    iconUrl: "/pets/scarlet-comet.png",
  },
  {
    slug: "earth-tyrant",
    name: "Earth Tyrant",
    iconUrl: "/pets/earth-tyrant.png",
  },
  {
    slug: "zathum",
    name: "Zathum",
    iconUrl: "/pets/zathum.png",
  },
  {
    slug: "blaze-monkey",
    name: "Blaze Monkey",
    iconUrl: "/pets/blaze-monkey.png",
  },
  {
    slug: "mecha-beetle",
    name: "Mecha Beetle",
    iconUrl: "/pets/mecha-beetle.png",
  },
  {
    slug: "tinman-no-7",
    name: "Tinman No.7",
    iconUrl: "/pets/tinman-no-7.png",
  },
  {
    slug: "stellar-whale",
    name: "Stellar Whale",
    iconUrl: "/pets/stellar-whale.png",
  },
  {
    slug: "rockturtle",
    name: "Rockturtle",
    iconUrl: "/pets/rockturtle.png",
  },
  {
    slug: "magic-owl",
    name: "Magic Owl",
    iconUrl: "/pets/magic-owl.png",
  },
  {
    slug: "giant-crabs",
    name: "Giant Crabs",
    iconUrl: "/pets/giant-crabs.png",
  },
  {
    slug: "yoyo-fox",
    name: "Yoyo Fox",
    iconUrl: "/pets/yoyo-fox.png",
  },
  {
    slug: "sparky",
    name: "Sparky",
    iconUrl: "/pets/sparky.png",
  },
  {
    slug: "kindwing",
    name: "Kindwing",
    iconUrl: "/pets/kindwing.png",
  },
  {
    slug: "mini-shroom",
    name: "Mini Shroom",
    iconUrl: "/pets/mini-shroom.png",
  },
  {
    slug: "emberling",
    name: "Emberling",
    iconUrl: "/pets/emberling.png",
  },
  {
    slug: "pea-fish",
    name: "Pea Fish",
    iconUrl: "/pets/pea-fish.png",
  },
];
