/** Names and icons from gameplay/relics; generated by scripts/slice-relics.py. */
export type RelicSeed = { slug: string; name: string; iconUrl: string };

export const relicSeeds: RelicSeed[] = [
  {
    slug: "night-twinblades",
    name: "Night Twinblades",
    iconUrl: "/relics/night-twinblades.png",
  },
  {
    slug: "charge-shield",
    name: "Charge Shield",
    iconUrl: "/relics/charge-shield.png",
  },
  {
    slug: "spiked-armor",
    name: "Spiked Armor",
    iconUrl: "/relics/spiked-armor.png",
  },
  {
    slug: "soulcalm-gem",
    name: "Soulcalm Gem",
    iconUrl: "/relics/soulcalm-gem.png",
  },
  {
    slug: "boots-of-haste",
    name: "Boots of Haste",
    iconUrl: "/relics/boots-of-haste.png",
  },
  {
    slug: "silverblade",
    name: "Silverblade",
    iconUrl: "/relics/silverblade.png",
  },
  {
    slug: "pendant-of-purity",
    name: "Pendant of Purity",
    iconUrl: "/relics/pendant-of-purity.png",
  },
  {
    slug: "arcane-cloak",
    name: "Arcane Cloak",
    iconUrl: "/relics/arcane-cloak.png",
  },
];
