/**
 * Weapon attribute catalog: every random additional attribute a weapon can
 * roll, read from the owner's "Possible Attributes" popups (gameplay/weapons).
 * Generated by scripts/import-weapon-attributes.py — edit CATALOG there, not
 * this file.
 */
export type WeaponAttributeSeed = {
  slug: string;
  name: string;
  sortOrder: number;
};

export const weaponAttributeSeeds: WeaponAttributeSeed[] = [
  { slug: "dmg-increase", name: "DMG Increase", sortOrder: 0 },
  { slug: "physical-dmg-boost", name: "Physical DMG Boost", sortOrder: 1 },
  { slug: "magic-dmg-boost", name: "Magic DMG Boost", sortOrder: 2 },
  { slug: "melee-dmg-boost", name: "Melee DMG Boost", sortOrder: 3 },
  { slug: "ranged-dmg-boost", name: "Ranged DMG Boost", sortOrder: 4 },
  { slug: "dmg-reduction", name: "DMG Reduction", sortOrder: 5 },
  { slug: "physical-res", name: "Physical RES", sortOrder: 6 },
  { slug: "magic-res", name: "Magic RES", sortOrder: 7 },
  { slug: "melee-dmg-reduct", name: "Melee DMG Reduct", sortOrder: 8 },
  { slug: "ranged-dmg-reduct", name: "Ranged DMG Reduct", sortOrder: 9 },
  { slug: "crit-rate", name: "CRIT Rate", sortOrder: 10 },
  { slug: "crit-damage", name: "CRIT Damage", sortOrder: 11 },
  { slug: "anti-control-rate", name: "Anti-Control Rate", sortOrder: 12 },
  { slug: "control-res", name: "Control RES", sortOrder: 13 },
  { slug: "spd-reduction-res", name: "SPD Reduction RES", sortOrder: 14 },
  { slug: "crit-dmg-res", name: "CRIT DMG RES", sortOrder: 15 },
  { slug: "anti-crit-rate", name: "Anti-CRIT Rate", sortOrder: 16 },
  { slug: "knockback-resist", name: "Knockback Resist", sortOrder: 17 },
  { slug: "knockback-effect", name: "Knockback Effect", sortOrder: 18 },
  { slug: "heavy-injury-effect", name: "Heavy Injury Effect", sortOrder: 19 },
  { slug: "atk-spd", name: "ATK SPD", sortOrder: 20 },
  { slug: "healing-effect", name: "Healing Effect", sortOrder: 21 },
  { slug: "receive-healing", name: "Receive Healing", sortOrder: 22 },
  { slug: "reflect-dmg", name: "Reflect DMG", sortOrder: 23 },
];
